# Generated by Django 4.2 on 2023-08-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('skill', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=50)),
                ('address', models.TextField()),
            ],
        ),
    ]
